### ISSUE TITLE
Inheritance does not work properly

### ISSUE THREAD

**Issue by jcn** [lucuma/sqlalchemy-wrapper#12]
Because `db.Model` explicitly defines `__tablename__`, STI doesn't work since the `declarative_base` expects `__tablename__` to be undefined to work properly.

http://docs.sqlalchemy.org/en/rel_1_0/orm/inheritance.html?highlight=inheritance#single-table-inheritance

flask-sqlalchemy actually had the same problem at one point and they fixed this by checking to see whether the table name should actually be set in different instances: https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L553-L591

**Comment by jcn** [comment]
My current workaround is to just use the `declarative_base()` as the model, as per #8 but this is obviously not ideal.

**Comment by jpscaletti** [comment]
Thank you very much for the bug report.

I'm detecting problems with [Joined Table Inheritance](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/declarative/inheritance.html#joined-table-inheritance), [Concrete Table Inheritance](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/declarative/inheritance.html#concrete-table-inheritance) and [Abstract Concrete Table Inheritance](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/declarative/inheritance.html#using-the-concrete-helpers) but not with [Single Table Inheritance](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/declarative/inheritance.html#single-table-inheritance).

An easy temporal fix is to manually define a ``__tablename__`` for each of your models.

I'm working on a permanent solution, probably adapted from the one from Flask-SQLAlchemy.

**Comment by jcn** [comment]
Thanks @jpscaletti. One thing I noticed is that I had to declare

`__table_args__ = {'extend_existing':True}`

on the classes in order to get STI to work properly. I didn't actually dig into it at all, but when inheriting from my base class, this seemed to be required. This is not necessary when using the `declarative_base()`.
